server:
  port: 10001
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedHeaders: "*"
            allowedOrigins: "*"
            allowedMethods: "*"
      default-filters:
        - PreserveHostHeader
    sentinel:
      filter:
        enabled: false
